package gnnt.MEBS.timebargain.server.engine.callAuction.impl;

import gnnt.MEBS.timebargain.server.model.Order;
import java.util.ArrayList;
import java.util.List;

class junanhuasheng
{
  public List<Order> getList1()
  {
    ArrayList localArrayList = new ArrayList();
    Order localOrder1 = new Order();
    localOrder1.setPrice(Double.valueOf(1850.0D));
    localOrder1.setQuantity(Long.valueOf(50L));
    localOrder1.setBuyOrSell(Short.valueOf((short)1));
    localOrder1.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder1);
    Order localOrder2 = new Order();
    localOrder2.setPrice(Double.valueOf(1840.0D));
    localOrder2.setQuantity(Long.valueOf(60L));
    localOrder2.setBuyOrSell(Short.valueOf((short)1));
    localOrder2.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder2);
    Order localOrder3 = new Order();
    localOrder3.setPrice(Double.valueOf(1830.0D));
    localOrder3.setQuantity(Long.valueOf(70L));
    localOrder3.setBuyOrSell(Short.valueOf((short)1));
    localOrder3.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder3);
    Order localOrder4 = new Order();
    localOrder4.setPrice(Double.valueOf(1820.0D));
    localOrder4.setQuantity(Long.valueOf(80L));
    localOrder4.setBuyOrSell(Short.valueOf((short)1));
    localOrder4.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder4);
    Order localOrder5 = new Order();
    localOrder5.setPrice(Double.valueOf(1810.0D));
    localOrder5.setQuantity(Long.valueOf(100L));
    localOrder5.setBuyOrSell(Short.valueOf((short)2));
    localOrder5.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder5);
    Order localOrder6 = new Order();
    localOrder6.setPrice(Double.valueOf(1820.0D));
    localOrder6.setQuantity(Long.valueOf(60L));
    localOrder6.setBuyOrSell(Short.valueOf((short)2));
    localOrder6.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder6);
    Order localOrder7 = new Order();
    localOrder7.setPrice(Double.valueOf(1830.0D));
    localOrder7.setQuantity(Long.valueOf(40L));
    localOrder7.setBuyOrSell(Short.valueOf((short)2));
    localOrder7.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder7);
    Order localOrder8 = new Order();
    localOrder8.setPrice(Double.valueOf(1840.0D));
    localOrder8.setQuantity(Long.valueOf(20L));
    localOrder8.setBuyOrSell(Short.valueOf((short)2));
    localOrder8.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder8);
    Order localOrder9 = new Order();
    localOrder9.setPrice(Double.valueOf(1850.0D));
    localOrder9.setQuantity(Long.valueOf(30L));
    localOrder9.setBuyOrSell(Short.valueOf((short)2));
    localOrder9.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder9);
    return localArrayList;
  }
  
  public List<Order> getList2()
  {
    ArrayList localArrayList = new ArrayList();
    Order localOrder1 = new Order();
    localOrder1.setPrice(Double.valueOf(8050.0D));
    localOrder1.setQuantity(Long.valueOf(50L));
    localOrder1.setBuyOrSell(Short.valueOf((short)1));
    localOrder1.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder1);
    Order localOrder2 = new Order();
    localOrder2.setPrice(Double.valueOf(8040.0D));
    localOrder2.setQuantity(Long.valueOf(30L));
    localOrder2.setBuyOrSell(Short.valueOf((short)1));
    localOrder2.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder2);
    Order localOrder3 = new Order();
    localOrder3.setPrice(Double.valueOf(8010.0D));
    localOrder3.setQuantity(Long.valueOf(50L));
    localOrder3.setBuyOrSell(Short.valueOf((short)2));
    localOrder3.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder3);
    Order localOrder4 = new Order();
    localOrder4.setPrice(Double.valueOf(8020.0D));
    localOrder4.setQuantity(Long.valueOf(50L));
    localOrder4.setBuyOrSell(Short.valueOf((short)2));
    localOrder4.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder4);
    Order localOrder5 = new Order();
    localOrder5.setPrice(Double.valueOf(8030.0D));
    localOrder5.setQuantity(Long.valueOf(50L));
    localOrder5.setBuyOrSell(Short.valueOf((short)2));
    localOrder5.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder5);
    Order localOrder6 = new Order();
    localOrder6.setPrice(Double.valueOf(8040.0D));
    localOrder6.setQuantity(Long.valueOf(40L));
    localOrder6.setBuyOrSell(Short.valueOf((short)2));
    localOrder6.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder6);
    Order localOrder7 = new Order();
    localOrder7.setPrice(Double.valueOf(8050.0D));
    localOrder7.setQuantity(Long.valueOf(20L));
    localOrder7.setBuyOrSell(Short.valueOf((short)2));
    localOrder7.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder7);
    return localArrayList;
  }
  
  public List<Order> getList3()
  {
    ArrayList localArrayList = new ArrayList();
    Order localOrder1 = new Order();
    localOrder1.setPrice(Double.valueOf(9060.0D));
    localOrder1.setQuantity(Long.valueOf(100L));
    localOrder1.setBuyOrSell(Short.valueOf((short)1));
    localOrder1.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder1);
    Order localOrder2 = new Order();
    localOrder2.setPrice(Double.valueOf(9050.0D));
    localOrder2.setQuantity(Long.valueOf(80L));
    localOrder2.setBuyOrSell(Short.valueOf((short)1));
    localOrder2.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder2);
    Order localOrder3 = new Order();
    localOrder3.setPrice(Double.valueOf(9030.0D));
    localOrder3.setQuantity(Long.valueOf(100L));
    localOrder3.setBuyOrSell(Short.valueOf((short)1));
    localOrder3.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder3);
    Order localOrder4 = new Order();
    localOrder4.setPrice(Double.valueOf(9020.0D));
    localOrder4.setQuantity(Long.valueOf(50L));
    localOrder4.setBuyOrSell(Short.valueOf((short)1));
    localOrder4.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder4);
    Order localOrder5 = new Order();
    localOrder5.setPrice(Double.valueOf(9010.0D));
    localOrder5.setQuantity(Long.valueOf(70L));
    localOrder5.setBuyOrSell(Short.valueOf((short)1));
    localOrder5.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder5);
    Order localOrder6 = new Order();
    localOrder6.setPrice(Double.valueOf(9000.0D));
    localOrder6.setQuantity(Long.valueOf(20L));
    localOrder6.setBuyOrSell(Short.valueOf((short)1));
    localOrder6.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder6);
    Order localOrder7 = new Order();
    localOrder7.setPrice(Double.valueOf(9000.0D));
    localOrder7.setQuantity(Long.valueOf(30L));
    localOrder7.setBuyOrSell(Short.valueOf((short)2));
    localOrder7.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder7);
    Order localOrder8 = new Order();
    localOrder8.setPrice(Double.valueOf(9010.0D));
    localOrder8.setQuantity(Long.valueOf(90L));
    localOrder8.setBuyOrSell(Short.valueOf((short)2));
    localOrder8.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder8);
    Order localOrder9 = new Order();
    localOrder9.setPrice(Double.valueOf(9030.0D));
    localOrder9.setQuantity(Long.valueOf(50L));
    localOrder9.setBuyOrSell(Short.valueOf((short)2));
    localOrder9.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder9);
    Order localOrder10 = new Order();
    localOrder10.setPrice(Double.valueOf(9040.0D));
    localOrder10.setQuantity(Long.valueOf(30L));
    localOrder10.setBuyOrSell(Short.valueOf((short)2));
    localOrder10.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder10);
    Order localOrder11 = new Order();
    localOrder11.setPrice(Double.valueOf(9060.0D));
    localOrder11.setQuantity(Long.valueOf(20L));
    localOrder11.setBuyOrSell(Short.valueOf((short)2));
    localOrder11.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder11);
    return localArrayList;
  }
  
  public List<Order> getList4()
  {
    ArrayList localArrayList = new ArrayList();
    Order localOrder1 = new Order();
    localOrder1.setPrice(Double.valueOf(9060.0D));
    localOrder1.setQuantity(Long.valueOf(100L));
    localOrder1.setBuyOrSell(Short.valueOf((short)1));
    localOrder1.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder1);
    Order localOrder2 = new Order();
    localOrder2.setPrice(Double.valueOf(9045.0D));
    localOrder2.setQuantity(Long.valueOf(80L));
    localOrder2.setBuyOrSell(Short.valueOf((short)1));
    localOrder2.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder2);
    Order localOrder3 = new Order();
    localOrder3.setPrice(Double.valueOf(9030.0D));
    localOrder3.setQuantity(Long.valueOf(100L));
    localOrder3.setBuyOrSell(Short.valueOf((short)1));
    localOrder3.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder3);
    Order localOrder4 = new Order();
    localOrder4.setPrice(Double.valueOf(9020.0D));
    localOrder4.setQuantity(Long.valueOf(50L));
    localOrder4.setBuyOrSell(Short.valueOf((short)1));
    localOrder4.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder4);
    Order localOrder5 = new Order();
    localOrder5.setPrice(Double.valueOf(9010.0D));
    localOrder5.setQuantity(Long.valueOf(70L));
    localOrder5.setBuyOrSell(Short.valueOf((short)1));
    localOrder5.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder5);
    Order localOrder6 = new Order();
    localOrder6.setPrice(Double.valueOf(9000.0D));
    localOrder6.setQuantity(Long.valueOf(20L));
    localOrder6.setBuyOrSell(Short.valueOf((short)1));
    localOrder6.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder6);
    Order localOrder7 = new Order();
    localOrder7.setPrice(Double.valueOf(9000.0D));
    localOrder7.setQuantity(Long.valueOf(30L));
    localOrder7.setBuyOrSell(Short.valueOf((short)2));
    localOrder7.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder7);
    Order localOrder8 = new Order();
    localOrder8.setPrice(Double.valueOf(9010.0D));
    localOrder8.setQuantity(Long.valueOf(90L));
    localOrder8.setBuyOrSell(Short.valueOf((short)2));
    localOrder8.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder8);
    Order localOrder9 = new Order();
    localOrder9.setPrice(Double.valueOf(9030.0D));
    localOrder9.setQuantity(Long.valueOf(50L));
    localOrder9.setBuyOrSell(Short.valueOf((short)2));
    localOrder9.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder9);
    Order localOrder10 = new Order();
    localOrder10.setPrice(Double.valueOf(9035.0D));
    localOrder10.setQuantity(Long.valueOf(30L));
    localOrder10.setBuyOrSell(Short.valueOf((short)2));
    localOrder10.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder10);
    Order localOrder11 = new Order();
    localOrder11.setPrice(Double.valueOf(9060.0D));
    localOrder11.setQuantity(Long.valueOf(20L));
    localOrder11.setBuyOrSell(Short.valueOf((short)2));
    localOrder11.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder11);
    return localArrayList;
  }
  
  public List<Order> getList5()
  {
    ArrayList localArrayList = new ArrayList();
    Order localOrder1 = new Order();
    localOrder1.setPrice(Double.valueOf(9060.0D));
    localOrder1.setQuantity(Long.valueOf(100L));
    localOrder1.setBuyOrSell(Short.valueOf((short)1));
    localOrder1.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder1);
    Order localOrder2 = new Order();
    localOrder2.setPrice(Double.valueOf(9045.0D));
    localOrder2.setQuantity(Long.valueOf(80L));
    localOrder2.setBuyOrSell(Short.valueOf((short)1));
    localOrder2.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder2);
    Order localOrder3 = new Order();
    localOrder3.setPrice(Double.valueOf(9030.0D));
    localOrder3.setQuantity(Long.valueOf(100L));
    localOrder3.setBuyOrSell(Short.valueOf((short)1));
    localOrder3.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder3);
    Order localOrder4 = new Order();
    localOrder4.setPrice(Double.valueOf(9020.0D));
    localOrder4.setQuantity(Long.valueOf(50L));
    localOrder4.setBuyOrSell(Short.valueOf((short)1));
    localOrder4.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder4);
    Order localOrder5 = new Order();
    localOrder5.setPrice(Double.valueOf(9010.0D));
    localOrder5.setQuantity(Long.valueOf(70L));
    localOrder5.setBuyOrSell(Short.valueOf((short)1));
    localOrder5.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder5);
    Order localOrder6 = new Order();
    localOrder6.setPrice(Double.valueOf(9000.0D));
    localOrder6.setQuantity(Long.valueOf(20L));
    localOrder6.setBuyOrSell(Short.valueOf((short)1));
    localOrder6.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder6);
    Order localOrder7 = new Order();
    localOrder7.setPrice(Double.valueOf(9000.0D));
    localOrder7.setQuantity(Long.valueOf(30L));
    localOrder7.setBuyOrSell(Short.valueOf((short)2));
    localOrder7.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder7);
    Order localOrder8 = new Order();
    localOrder8.setPrice(Double.valueOf(9010.0D));
    localOrder8.setQuantity(Long.valueOf(90L));
    localOrder8.setBuyOrSell(Short.valueOf((short)2));
    localOrder8.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder8);
    Order localOrder9 = new Order();
    localOrder9.setPrice(Double.valueOf(9030.0D));
    localOrder9.setQuantity(Long.valueOf(50L));
    localOrder9.setBuyOrSell(Short.valueOf((short)2));
    localOrder9.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder9);
    Order localOrder10 = new Order();
    localOrder10.setPrice(Double.valueOf(9036.0D));
    localOrder10.setQuantity(Long.valueOf(30L));
    localOrder10.setBuyOrSell(Short.valueOf((short)2));
    localOrder10.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder10);
    Order localOrder11 = new Order();
    localOrder11.setPrice(Double.valueOf(9060.0D));
    localOrder11.setQuantity(Long.valueOf(20L));
    localOrder11.setBuyOrSell(Short.valueOf((short)2));
    localOrder11.setOrderType(Short.valueOf((short)1));
    localArrayList.add(localOrder11);
    return localArrayList;
  }
}
