package gnnt.MEBS.config.constant;

public class NumberDigits
{
  public static int MINRISKFUND = 2;
  public static int WARNTH = 4;
  public static int FROZENTH = 4;
  public static int M_SELF = 4;
  public static int CU_F_WARNTH = 2;
  public static int M_CU_BALANCESUM = 2;
  public static int NETFL = 2;
  public static int SPECIALMINRISKFUND = 2;
  public static int SPECIALWARNTH = 4;
  public static int FEERATE = 6;
  public static int MKT_FEERATE = 6;
  public static int C_WARNTH = 4;
  public static int C_FORCETH = 4;
  public static int M_WARNTH = 4;
  public static int M_FROZENTH = 4;
  public static int SM_FROZENTH = 4;
  public static int M_SELFTRADERATE = 4;
  public static int CM_MINRISKFUND = 2;
  public static int BM_MINRISKFUND = 2;
  public static int SM_WARNTH = 4;
  public static int SM_MINRISKFUND = 2;
  public static int QUOTERATE = 6;
  public static int QUOTEEXCHANGERATE = 4;
  public static int CLEAREXCHAGERATE = 6;
  public static int QUOTEAGIO = 2;
  public static int CONTRACTFACTOR = 2;
  public static int MINHQMOVE = 4;
  public static int MINPRICEMOVE = 4;
  public static int STEPMOVE = 4;
  public static int SPREADUPLMT = 2;
  public static int SPREADDOWNLMT = 2;
  public static int LASTPRICE = 2;
  public static int SCREENINGPRICEPOINT = 4;
  public static int TRADEMARGIN = 4;
  public static int SETTLEMARGIN = 4;
  public static int HOLIDAYMARGIN = 4;
  public static int STOPLOSSPOINT = 2;
  public static int STOPPROFITPOINT = 2;
  public static int L_OPEN_POINT = 2;
  public static int M_ORDERPOINT = 2;
  public static int MIN_M_ORDERPOINT = 2;
  public static int MAX_M_ORDERPOINT = 2;
  public static int QUOTEPOINT_B_RATE = 6;
  public static int QUOTEPOINT_S_RATE = 6;
  public static int DELAYFEE = 6;
  public static int STEPRATE = 4;
  public static int RMB = 2;
  public static int FUNDS = 2;
}
